### ISSUE TITLE
ES6 features not working

### ISSUE THREAD

**Issue by michalsanger** [serverless/serverless-graphql-blog#2]
There is probably some custom setup on your machine, I can't get it working after this commands (node v5.4.1):

```
git clone git@github.com:serverless/serverless-graphql-blog.git .
sls project init -c
sls function run blog/resource/graphql
```

I get this error `Serverless: SyntaxError: Unexpected token import`. Obviously Babel transformation was not called.

What worked for me was:

```
npm install babel-register babel-preset-es2015 aws-sdk
echo '{"presets": ["es2015"]}' > .babelrc
```

and add `require("babel-register");` into `graphql/handler.js`. Then I can see "Success":

```
$ sls function run blog/resource/graphql
Serverless: Running blog/resource/graphql...  
Serverless: -----------------  
Serverless: Success! - This Response Was Returned:  
Serverless: {"errors":[{"message":"Syntax Error GraphQL request (1:1) Unexpected EOF\n\n1: \n   ^\n"}]}  
```

Don't have AWS account yet, so I'm not sure if there is any trap in deploy. I'll be happy to send pull request, but maybe you have better solution since I'm no big expert in Serverless & NodeJS.

**Comment by kevinold** [comment]
Unfortunately, this is not yet working with `sls function run`.  Once you add the .babelrc and the babe-register, it does work correctly as you get an error from GraphQL (which means it compiles).  

That said, at the moment it's meant to be tested once deployed and I'm not planning to focus on any local development since the ultimate queries to the data source are against DynamoDB.
